const express = require('express')
const morgan = require('morgan')
const app = express()
// const fileUpload = require('express-fileupload');
const fileMiddleware = require('express-multipart-file-parser')

const cwd = process.cwd();
var cors = require('cors')
// const bodyParser = require('body-parser')
const {AdminApp} = require('./Admin_app/Admin-app')
const {SettingsApp} = require('./Settings-app/Settings-app')
const {ColorsApp} = require('./Colors-app/Color-app')
const { apiResponse } = require('../Utils/Common/APIResponce')
const {CurrencysApp} = require('./Currency-app/Currency-app')
const {BranchApp} = require('./Branch-app/Branch-app')
const {BaristaApp} = require('./BaristaApp/Barista-app')
const {CategoryApp} = require('./Category_app/category-app')
const {CatelougeApp} = require('./InventoryCatelougesApp/catelouge-app')
const {setupApp} = require("./SetupApp/setup-app")
const {ProductsApp} = require("./ProductApp/product-app")
const {InventoryOrdersApp} = require('./InventoryOrderApp/inventory-order-app')
const {ExpenseApp} = require("./ExpenseApp/Expense-app")
const {TxnOutApp} = require("./Transaction-outApp/transaction-out-out-app")
const {InventoryReportApp} = require('./Inventory-report/inventory-report-app')
const {OrdersApp} = require("./OrdersApp/orders-app")
const {UserApp} = require("./User_App/User-App")
const {UserCategoryApp} = require('./SHARAFA-USER APP/Category_app/category-app')
const {ModifiersApp} = require('./SHARAFA-USER APP/ModifiersApp/modifier-app')
const {UserProductApp} = require('./SHARAFA-USER APP/Products_app/products-app')
const {EventApp} = require('./SHARAFA-USER APP/eventsApp/events-app')
const {StoryApp} = require('./SHARAFA-USER APP/storyApp/story-app')
app.use(cors())
app.use(express.urlencoded({extended : false}))
app.use(express.json())
app.use(morgan('dev'))
app.use(apiResponse)
app.use(express.static(cwd + '/dist'));
app.use(express.static(cwd + '/media'));
app.use(fileMiddleware)

/* Api Middleware */
EventApp(app)
OrdersApp(app)
InventoryReportApp(app)
TxnOutApp(app)
ExpenseApp(app)
InventoryOrdersApp(app)
setupApp(app)
ProductsApp(app)
CatelougeApp(app)
CategoryApp(app)
BaristaApp(app)
BranchApp(app)
CurrencysApp(app)
UserApp(app)
AdminApp(app)
SettingsApp(app)
ColorsApp(app)
UserCategoryApp(app)
ModifiersApp(app)
UserProductApp(app)
StoryApp(app)
module.exports.app = app
